on:
  push:
    branches:
      - main
name: Deploy Website via FTP
jobs:
  web-deploy:
    name: Deploy website
    runs-on: ubuntu-latest
    steps:
    - name: Get the latest code
      uses: actions/checkout@v3

    - name: Push files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp.bisinet.xyz
        username: ftpuser@bisinet.xyz
        password: ${{ secrets.ftp_password }}
